<IOCSR_DATA=random>     //random, zero, one
<IOCSR_FRAME=64>        //count in dword, 252 and 100
<IOCSR_PAD=0>           //count in dword, the number showing here is in decimal
<CORE_DATA=random>      //random, zero, one
<CORE_FRAME=100>        //size in dword, the number showing here is in decimal
<CORE_FT=28>            // the number showing here is in Hex
<CORE_SL=65>            // the number showing here is in Hex
<CORE_WIDTH=8>                                           // core width 8/16
<CORE_SEG=16>                                               // core bitstream segmentation 8/16/32
<CORE_1ST=Y>                                  // First Core Frame? Y/N
<OUTPUT_FILENAME=spi.dat>   //SPI POF Image File Name
<SDM_IOCSR_FILE=sdm_iocsr.dat>          //SDM IOCSR POF Image File Name
<SDM_CORE_FILE=sdm_core.dat>            //SDM CORE POF Image File Name
<IOCSRCFF_FILE=iocsr.cff>               //IOCSR expected output file name
<CORECFF_FILE=core.cff>                                 //CORE expected output file name
